action-webservice:
  host: localhost
  port: 8151

case-webservice:
  host: localhost
  port: 8171

ldap-directory:
  host: ldap-server
  port: 389
  base: dc=ctp,dc=ons,dc=gov,dc=uk
  groups:
    admins: collect-admins
    users: collect-users
    csos: collect-csos

badges:
  built: 01_Jan_1970
  commit: commit
  environment: development
