http:
  protocol: http

action-webservice:
  host: collect-server
  port: 8151

case-webservice:
  host: collect-server
  port: 8171

action-exporter-webservice:
  host: collect-server
  port: 8141
  user: actionexporter
  password: ctp

reports:
  host:
    action: collect-server
    case: collect-server
  port:
    action: 8141
    case: 8171
  auth:
    action: true
    case: false

ldap-directory:
  host: ldap-server
  port: 389
  base: dc=ctp,dc=ons,dc=gov,dc=uk
  groups:
    users: collect-users

badges:
  built: 01_Jan_1970
  commit: commit
  environment: development
