http:
  protocol: http

action-exporter-webservice:
  host: collect-server
  port: 8141

action-webservice:
  host: collect-server
  port: 8151

case-webservice:
  host: collect-server
  port: 8171

ldap-directory:
  host: ldap-server
  port: 636
  base: dc=ctp,dc=ons,dc=gov,dc=uk
  groups:
    users: collect-users

badges:
  built: 01_Jan_1970
  commit: commit
  environment: development
