follow-up-webservice:
  host: collect-server
  port: 8177

frame-webservice:
  host: collect-server
  port: 8171

response-generator-webservice:
  host: collect-server
  port: 8168

ldap-directory:
  host: ldap-server
  port: 389
  base: dc=ctp,dc=ons,dc=gov,dc=uk

google-maps:
  api-key: AIzaSyAtKmYXuijfiPsstjNsczBocKw149--fqM
