follow-up-webservice:
  host: collect-server
  port: 8177

frame-webservice:
  host: collect-server
  port: 8171

response-generator-webservice:
  host: collect-server
  port: 8168

google-maps:
  api-key: AIzaSyAtKmYXuijfiPsstjNsczBocKw149--fqM
