follow-up-webservice:
  host: collect-server
  port: 8177

action-webservice:
  host: collect-server
  port: 8161

frame-webservice:
  host: collect-server
  port: 8171

response-generator-webservice:
  host: collect-server
  port: 8168

ldap-directory:
  host: ldap-server
  port: 389
  base: dc=ctp,dc=ons,dc=gov,dc=uk
  groups:
    admins: collect-admins
    users: collect-users
    csos: collect-csos

google-maps:
  api-key: AIzaSyAtKmYXuijfiPsstjNsczBocKw149--fqM

badges:
  built: 01_Jan_1970
  commit: commit
  environment: development
