follow-up-webservice:
  host: collect-server
  port: 8177

frame-webservice:
  host: collect-server
  port: 8171

ldap-directory:
  host: ldap-server
  port: 389

google-maps:
  api-key: AIzaSyAtKmYXuijfiPsstjNsczBocKw149--fqM

database:
  host: fuse-server
  name: postgres
  user: postgres
  password: p0stgr3s
